Repository nismod/smif, pull requests merged in 2018-10, with the labels that each got.

#232 Feature/gui validation
  src/smif/app/src/actions/actions.js
  src/smif/app/src/components/ConfigForm/SosModelConfigForm.js
  src/smif/app/src/containers/Configuration/Forms/SosModelConfig.js
  src/smif/app/src/containers/Configuration/Overview/ProjectOverview.js
  src/smif/app/src/reducers/reducers.js
  src/smif/app/static/css/main.css
  src/smif/data_layer/data_interface.py
  src/smif/data_layer/datafile_interface.py
  src/smif/data_layer/validate.py
  src/smif/exception.py
  src/smif/http_api/crud.py
  tests/data_layer/conftest.py
  tests/data_layer/test_interface_implementations.py
  tests/data_layer/test_validate.py
  tests/http_api/test_crud.py
Labels: in progress

#235 Add narratives to sos model configuration
  src/smif/data_layer/data_handle.py
  src/smif/data_layer/data_interface.py
  src/smif/data_layer/database_interface.py
  src/smif/data_layer/datafile_interface.py
  src/smif/data_layer/memory_interface.py
  src/smif/model/sos_model.py
  src/smif/sample_project/config/model_runs/energy_central.yml
  src/smif/sample_project/config/model_runs/energy_water_cp_cr.yml
  src/smif/sample_project/config/narratives/technology.yml
  src/smif/sample_project/config/sos_models/energy.yml
  src/smif/sample_project/config/sos_models/energy_water.yml
  tests/conftest.py
  tests/controller/test_modelrun.py
  tests/data_layer/conftest.py
  tests/data_layer/test_data_handle.py
  tests/data_layer/test_datafile_interface.py
  tests/data_layer/test_interface_implementations.py
  tests/model/test_sos_model.py
Labels: enhancement

#237 Feature/dataarray
  .appveyor.yml
  .environment.yml
  ci/install.sh
  docs/conf.py
  requirements-docs.txt
  requirements.txt
  setup.cfg
  src/smif/data_layer/data_array.py
  src/smif/data_layer/data_handle.py
  src/smif/data_layer/data_interface.py
  src/smif/data_layer/database_interface.py
  src/smif/data_layer/datafile_interface.py
  src/smif/data_layer/memory_interface.py
  src/smif/model/model.py
  src/smif/sample_project/models/energy_demand.py
  tests/conftest.py
  tests/data_layer/conftest.py
  tests/data_layer/test_data_array.py
  tests/data_layer/test_data_handle.py
  tests/data_layer/test_data_interface.py
  tests/data_layer/test_datafile_interface.py
  tests/data_layer/test_interface_implementations.py
  tests/model/test_sector_model.py
Labels: enhancement, ready for review
